In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\AI Code\NLP\Duplicate Question Pairs\train.csv\train.csv")
df.shape

(404290, 6)

In [3]:
new_df = df.sample(30000)

In [4]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [5]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
30526,Why does India have bad bureaucrats?,Who is the most corrupt bureaucrat in India?
152547,What is the meaning of life?,"What does the term ""meaning of life"" mean?"
112884,What are examples of things that use electroma...,What are examples of devices that use electrom...
358780,Why doesn't YouTube play videos on my iPad?,What should I do if videos won't play on YouTube?
296246,What would happen if Kim Jong-un died?,What will happen if Kim Jong-Un is killed?

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [7]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [8]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
30526,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
358780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
296246,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28927,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
301749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
202014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7441666666666666

In [13]:
import joblib
# Save the model
joblib.dump(rf, "rf_only_bow_model.joblib")

['rf_only_bow_model.joblib']